/*
	TblTblDataServiceExample.m
	Provides example and test runs the service's proxy methods.
	Generated by SudzC.com
*/
#import "TblTblDataServiceExample.h"
#import "TblTblDataService.h"

@implementation TblTblDataServiceExample

- (void)run {
	// Create the service
	TblTblDataService* service = [TblTblDataService service];
	service.logging = YES;
	// service.username = @"username";
	// service.password = @"password";
	

	// Returns TblPlayerStatsDto*. 
	[service GetAllPlayerStats:self action:@selector(GetAllPlayerStatsHandler:) id: 0];

	// Returns NSMutableArray*. 
	[service GetFixturesFiltered:self action:@selector(GetFixturesFilteredHandler:) teamId: 0 isPlayed: @""];

	// Returns NSMutableArray*. 
	[service GetLatestMatchResults:self action:@selector(GetLatestMatchResultsHandler:) numberOfMatchResults: 0];

	// Returns TblMatchResultDto*. 
	[service GetMatchResult:self action:@selector(GetMatchResultHandler:) fixtureId: 0];

	// Returns NSMutableArray*. 
	[service GetNews:self action:@selector(GetNewsHandler:) numberOfArticles: 0];

	// Returns TblLeagueStandingsDto*. 
	[service GetStandingsForCurrentSeason:self action:@selector(GetStandingsForCurrentSeasonHandler:)];

	// Returns TblTeam*. 
	[service GetTeam:self action:@selector(GetTeamHandler:) id: 0];

	// Returns NSMutableArray*. 
	[service GetTeamsForCurrentSeason:self action:@selector(GetTeamsForCurrentSeasonHandler:)];

	// Returns NSMutableArray*. 
	[service GetTeamsNamesForCurrentSeason:self action:@selector(GetTeamsNamesForCurrentSeasonHandler:)];

	// Returns id. 
	[service TestError:self action:@selector(TestErrorHandler:)];
}

	

// Handle the response from GetAllPlayerStats.
		
- (void) GetAllPlayerStatsHandler: (id) value {

	// Handle errors
	if([value isKindOfClass:[NSError class]]) {
		NSLog(@"%@", value);
		return;
	}

	// Handle faults
	if([value isKindOfClass:[SoapFault class]]) {
		NSLog(@"%@", value);
		return;
	}				
			

	// Do something with the TblPlayerStatsDto* result
		TblPlayerStatsDto* result = (TblPlayerStatsDto*)value;
	NSLog(@"GetAllPlayerStats returned the value: %@", result);
			
}
	

// Handle the response from GetFixturesFiltered.
		
- (void) GetFixturesFilteredHandler: (id) value {

	// Handle errors
	if([value isKindOfClass:[NSError class]]) {
		NSLog(@"%@", value);
		return;
	}

	// Handle faults
	if([value isKindOfClass:[SoapFault class]]) {
		NSLog(@"%@", value);
		return;
	}				
			

	// Do something with the NSMutableArray* result
		NSMutableArray* result = (NSMutableArray*)value;
	NSLog(@"GetFixturesFiltered returned the value: %@", result);
			
}
	

// Handle the response from GetLatestMatchResults.
		
- (void) GetLatestMatchResultsHandler: (id) value {

	// Handle errors
	if([value isKindOfClass:[NSError class]]) {
		NSLog(@"%@", value);
		return;
	}

	// Handle faults
	if([value isKindOfClass:[SoapFault class]]) {
		NSLog(@"%@", value);
		return;
	}				
			

	// Do something with the NSMutableArray* result
		NSMutableArray* result = (NSMutableArray*)value;
	NSLog(@"GetLatestMatchResults returned the value: %@", result);
			
}
	

// Handle the response from GetMatchResult.
		
- (void) GetMatchResultHandler: (id) value {

	// Handle errors
	if([value isKindOfClass:[NSError class]]) {
		NSLog(@"%@", value);
		return;
	}

	// Handle faults
	if([value isKindOfClass:[SoapFault class]]) {
		NSLog(@"%@", value);
		return;
	}				
			

	// Do something with the TblMatchResultDto* result
		TblMatchResultDto* result = (TblMatchResultDto*)value;
	NSLog(@"GetMatchResult returned the value: %@", result);
			
}
	

// Handle the response from GetNews.
		
- (void) GetNewsHandler: (id) value {

	// Handle errors
	if([value isKindOfClass:[NSError class]]) {
		NSLog(@"%@", value);
		return;
	}

	// Handle faults
	if([value isKindOfClass:[SoapFault class]]) {
		NSLog(@"%@", value);
		return;
	}				
			

	// Do something with the NSMutableArray* result
		NSMutableArray* result = (NSMutableArray*)value;
	NSLog(@"GetNews returned the value: %@", result);
			
}
	

// Handle the response from GetStandingsForCurrentSeason.
		
- (void) GetStandingsForCurrentSeasonHandler: (id) value {

	// Handle errors
	if([value isKindOfClass:[NSError class]]) {
		NSLog(@"%@", value);
		return;
	}

	// Handle faults
	if([value isKindOfClass:[SoapFault class]]) {
		NSLog(@"%@", value);
		return;
	}				
			

	// Do something with the TblLeagueStandingsDto* result
		TblLeagueStandingsDto* result = (TblLeagueStandingsDto*)value;
	NSLog(@"GetStandingsForCurrentSeason returned the value: %@", result);
			
}
	

// Handle the response from GetTeam.
		
- (void) GetTeamHandler: (id) value {

	// Handle errors
	if([value isKindOfClass:[NSError class]]) {
		NSLog(@"%@", value);
		return;
	}

	// Handle faults
	if([value isKindOfClass:[SoapFault class]]) {
		NSLog(@"%@", value);
		return;
	}				
			

	// Do something with the TblTeam* result
		TblTeam* result = (TblTeam*)value;
	NSLog(@"GetTeam returned the value: %@", result);
			
}
	

// Handle the response from GetTeamsForCurrentSeason.
		
- (void) GetTeamsForCurrentSeasonHandler: (id) value {

	// Handle errors
	if([value isKindOfClass:[NSError class]]) {
		NSLog(@"%@", value);
		return;
	}

	// Handle faults
	if([value isKindOfClass:[SoapFault class]]) {
		NSLog(@"%@", value);
		return;
	}				
			

	// Do something with the NSMutableArray* result
		NSMutableArray* result = (NSMutableArray*)value;
	NSLog(@"GetTeamsForCurrentSeason returned the value: %@", result);
			
}
	

// Handle the response from GetTeamsNamesForCurrentSeason.
		
- (void) GetTeamsNamesForCurrentSeasonHandler: (id) value {

	// Handle errors
	if([value isKindOfClass:[NSError class]]) {
		NSLog(@"%@", value);
		return;
	}

	// Handle faults
	if([value isKindOfClass:[SoapFault class]]) {
		NSLog(@"%@", value);
		return;
	}				
			

	// Do something with the NSMutableArray* result
		NSMutableArray* result = (NSMutableArray*)value;
	NSLog(@"GetTeamsNamesForCurrentSeason returned the value: %@", result);
			
}
	

// Handle the response from TestError.
		
- (void) TestErrorHandler: (id) value {

	// Handle errors
	if([value isKindOfClass:[NSError class]]) {
		NSLog(@"%@", value);
		return;
	}

	// Handle faults
	if([value isKindOfClass:[SoapFault class]]) {
		NSLog(@"%@", value);
		return;
	}				
			

	// Do something with the id result
		id result = (id)value;
	NSLog(@"TestError returned the value: %@", result);
			
}
	

@end
		